package db

import (
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
)

type BaseStruct struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// FillCreatedAtUpdatedAt sets created_at (if not already set) and updated_at to the current time.
func (b *BaseStruct) FillCreatedAtUpdatedAt() {
	now := time.Now()
	if b.CreatedAt.IsZero() {
		b.CreatedAt = now
	}

	b.UpdatedAt = now
}

// GetInsertQuery appends created_at and updated_at columns and their placeholders
// to a base INSERT query of the form "INSERT INTO table (cols) VALUES (vals)".
// It assumes IDs are auto-generated by the database.
func (b *BaseStruct) GetInsertQuery(baseQuery string, args []any) (string, []any) {
	n := len(args)
	b.FillCreatedAtUpdatedAt()
	args = append(args, b.CreatedAt, b.UpdatedAt)

	// Find the closing paren of the column list and the value list.
	colClose := strings.Index(baseQuery, ")")
	valClose := strings.LastIndex(baseQuery, ")")

	query := baseQuery[:colClose] + ", created_at, updated_at)" +
		baseQuery[colClose+1:valClose] +
		fmt.Sprintf(", $%d, $%d)", n+1, n+2)

	return query, args
}
