tlsConfig:
  certFile: "${TLS_CERT_FILE}"
  keyFile: "${TLS_KEY_FILE}"
database:
  host: "${DB_HOST}"
  name: "${DB_NAME}"
  password: "${DB_PASSWORD}"
  port: ${DB_PORT}
  user: "${DB_USER}"
  sslMode: "disable"
jwt:
  secret: "${JWT_SECRET}"
google:
  auth_secret: "${GOOGLE_AUTH_SECRET}"
  auth_client_id: "${GOOGLE_AUTH_CLIENT_ID}"